
# 添加QT
#set(CMAKE_AUTOUIC ON)
#set(CMAKE_AUTOMOC ON)
#set(CMAKE_AUTORCC ON)

set(SS_QT_VERSION_MAJOR 6)

if (${SS_QT_VERSION_MAJOR} EQUAL 6)
    find_package(QT NAMES Qt6 COMPONENTS Gui Widgets OpenGL OpenGLWidgets REQUIRED)
    find_package(Qt6 6.4.2 COMPONENTS Gui Widgets OpenGL OpenGLWidgets REQUIRED)
    if (Qt6_FOUND)
        message(STATUS "The Qt${QT_VERSION_MAJOR} lib is found!")
        message (STATUS "Qt version: ${Qt6Widgets_VERSION}")
        message (STATUS "Qt path: ${Qt6Widgets_DIR}")
    else ()
        message(STATUS "The Qt${QT_VERSION_MAJOR} lib is no found!")
    endif ()
else ()
    find_package(QT NAMES Qt5 COMPONENTS Gui Widgets OpenGL OpenGLWidgets REQUIRED)
    find_package(Qt5 COMPONENTS Gui Widgets OpenGL OpenGLWidgets REQUIRED)
    if (Qt5_FOUND)
        message(STATUS "The Qt${QT_VERSION_MAJOR} lib is found!")
        message (STATUS "Qt version: ${Qt5Widgets_VERSION}")
        message (STATUS "Qt path: ${Qt5Widgets_DIR}")
    else ()
        message(STATUS "The Qt${QT_VERSION_MAJOR} lib is no found!")
    endif ()
endif ()
